In [8]:
#bubble sort

def bubblesort(arr):
  n = len(arr)
  for i in range(n):
    for j in range(0,n-i-1):
      if arr[j]>arr[j+1]:
        arr[j],arr[j+1] = arr[j+1],arr[j]
  return arr

In [9]:
import numpy as np
arr = np.array([2,1,11,7,3,14,6])
bubblesort(arr)

array([ 1,  2,  3,  6,  7, 11, 14])

In [10]:
#selection sort -> repeatedly selects the smallest or largest and swaps
def selectionsort(arr):
  n = len(arr)
  for i in range(n):
    min_idx = i
    for j in range(i+1,n):
      if arr[j]<arr[min_idx]:
        min_idx = j
    arr[i],arr[min_idx]= arr[min_idx],arr[i]
  return arr

In [11]:
import numpy as np
arr = np.array([3,1,9,5,16,12])
selectionsort(arr)

array([ 1,  3,  5,  9, 12, 16])

In [12]:
#insertion sort -> finding minimum one and inserting at starting it builds by sorting one element at a time
def insertionsort(arr):
  n = len(arr)
  for i in range(1,n):
    key = arr[i]
    j = i-1
    while j>=0 and key<arr[j]:
      arr[j+1] = arr[j]
      j -= 1
    arr[j+1] = key
  return arr

In [13]:
import numpy as np
arr = np.array([3,1,9,5,16,12])
insertionsort(arr)

array([ 1,  3,  5,  9, 12, 16])